#
# Copyright (c) 2014, Texas lake Development Board
# All rights reserved.
#
# This code is open-source. See LICENSE file for details.
#

from traits.api import Interface, Array, Dict, Event, Property


class ISurveyLine(Interface):
    """ A class representing a single survey line """

    #: sample locations, an Nx2 array of lat/long (or easting/northing?)
    locations = Array(shape=(None, 2))

    #: a dictionary mapping frquencies to intensity arrays
    frequencies = Dict

    #: depth of the lake at each location generated algorithmically
    algorithmic_lake_depths = Array

    #: depth of lake at each location generated by user
    #: values which the user has not edited should be NaN
    user_lake_depths = Array

    # the combination of the user and algorithmic lake depths
    lake_depths = Property(Array, depends_on='lake_depth_updated')

    # and event fired when the lake depth is updated
    lake_depth_updated = Event

    #: pre-impoundment depths at each location generated algorithmically
    algorithmic_preimpoundment_depths = Array

    #: pre-impoundment depths at each location generated by user
    #: values which the user has not edited should be NaN
    user_preimpoundment_depths = Array

    # the combination of the user and algorithmic preimpoundment depths
    preimpoundment_depths = Property(Array, depends_on='preimpoundment_depth_updated')

    # and event fired when the preimpoundment depth is updated
    preimpoundment_depth_updated = Event

    # XXX probably other metadata should be here
