#
# Copyright (c) 2014, Texas Water Development Board
# All rights reserved.
#
# This code is open-source. See LICENSE file for details.
#

from __future__ import absolute_import

import os
import numpy as np
from shapely.geometry import LineString

<<<<<<< HEAD
from traits.api import (HasTraits, Array, Dict, Event, List, Supports, Str,
                        provides, CFloat, Instance)

from sdi import binary

=======
from traits.api import (HasTraits, Array, Dict, Event, Instance, List,
                        Supports, Str, provides, CFloat, Tuple)
>>>>>>> feature/plot_cores

from .i_core_sample import ICoreSample
from .i_survey_line import ISurveyLine
from .i_depth_line import IDepthLine
from .depth_line import DepthLine


@provides(ISurveyLine)
class SurveyLine(HasTraits):
    """ A class representing a single survey line """

    #: the user-visible name for the line
    name = Str

    #: sample locations, an Nx2 array (example: easting/northing?)
    locations = Array(shape=(None, 2))

    #: specifies unit for values in locations array
    locations_unit = Str('feet')

    #: array of associated lat/long available for display
    lat_long = Array(shape=(None, 2))

    #: a dictionary mapping frequencies to intensity arrays
    frequencies = Dict

    #: complete trace_num set. array = combined freq_trace_num arrays
    trace_num = Array

    #: array of trace numbers corresponding to each intensity pixel/column
    #: ! NOTE ! starts at 1, not 0, so need to subtract 1 to use as index
    freq_trace_num = Dict

    #: relevant core samples
    core_samples = List(Supports(ICoreSample))

    #: depth of the lake at each location as generated by various soruces
    lake_depths = Dict(Str, Supports(IDepthLine))

    # and event fired when the lake depths are updated
    lake_depths_updated = Event

    #: The navigation track of the survey line in map coordinates
    navigation_line = Instance(LineString)

    #: pre-impoundment depth at each location as generated by various soruces
    preimpoundment_depths = Dict(Str, Supports(IDepthLine))

    # and event fired when the lake depth is updated
    preimpoundment_depths_updated = Event

    # power values for entire trace set
    power = Array

    # gain values for entire trace set
    gain = Array

    #: Depth corrections:
    #:  depth = (pixel_number_from_top * pixel_resolution) + draft - heave
    #: distance from sensor to water. Constant offset added to depth
    draft = CFloat

    #: array of depth corrections.  Changes vertical offset of each column.
    heave = Array

    #: pixel resolution, depth/pixel
    pixel_resolution = CFloat

    # XXX probably other metadata should be here

    def load_data(self, hdf5_file):
        ''' Called by UI to load this survey line when selected to edit
        '''
<<<<<<< HEAD
        # read in sdi dictionary.  Only use 'frequencies' item.
        sdi_dict_separated = binary.read(self.data_file_path)
        sdi_dict_raw = binary.read(self.data_file_path, separate=False)
        freq_dict_list = sdi_dict_separated['frequencies']
=======
        from ..io import survey_io

        # read frequency dict from hdf5 file.
        freq_dict_list = survey_io.read_frequency_data_from_hdf(hdf5_file, self.name)
>>>>>>> feature/plot_cores

        # fill frequncies and freq_trace_num dictionaries with freqs as keys.
        for freq_dict in freq_dict_list:
            key = freq_dict['kHz']
            # transpose array to go into image plot correctly oriented
            intensity = freq_dict['intensity'].T
            self.frequencies[str(key)] = intensity
<<<<<<< HEAD
            self.freq_trace_num[str(key)] = freq_dict['trace_num']

        # for all other traits, use un-freq-sorted values
        self.trace_num = sdi_dict_raw['trace_num']
        self.locations = np.vstack([sdi_dict_raw['interpolated_easting'],
                                   sdi_dict_raw['interpolated_northing']]).T
        self.lat_long = np.vstack([sdi_dict_raw['latitude'],
                                  sdi_dict_raw['longitude']]).T
        self.draft = (np.mean(sdi_dict_raw['draft']))
        self.heave = sdi_dict_raw['heave']
        self.pixel_resolution = (np.mean(sdi_dict_raw['pixel_resolution']))
        self.power = sdi_dict_raw['power']
        self.gain = sdi_dict_raw['gain']
        # create depth line from sdi depth_r1 data and add to lakedepth dict
        sdi_depth_line_data = sdi_dict_raw['depth_r1']
        filename = os.path.basename(sdi_dict_raw['filepath'])
        depth_line = DepthLine(survey_line_name=self.name,
                               name='depth_r1',
                               line_type='current surface',
                               source='sdi_file',
                               source_name=filename,
                               index_array=self.trace_num - 1,
                               depth_array=sdi_depth_line_data,
                               color='blue')
        self.lake_depths[depth_line.name] = depth_line
=======
            self.shape = intensity.shape
            lake_key = 'Lakedepth_{:.1f}'.format(key)
            self.lake_depths[lake_key] = freq_dict['depth_r1']

        # for all other traits, take from first freq, assuming identical
        freq_dict = freq_dict_list[0]
        self.locations = np.vstack([freq_dict['interpolated_easting'],
                                   freq_dict['interpolated_northing']]).T
        self.lat_long = np.vstack([freq_dict['latitude'],
                                  freq_dict['longitude']]).T
        self.draft = (np.mean(freq_dict['draft']))
        self.heave = freq_dict['heave']
        self.pixel_resolution = (np.mean(freq_dict['pixel_resolution']))

    def nearby_core_samples(self, core_samples, dist_tol=100):
        """ Find core samples from a list of CoreSample instances
        that lie within dist_tol units of this survey line.
        """
        def distance(core, line):
            """ Calculate distance between a core sample and a survey line
            """
            from shapely.geometry import Point
            return self.navigation_line.distance(Point(core.location))
        return [core for core in core_samples if distance(core, self) < dist_tol]
>>>>>>> feature/plot_cores
